### ISSUE TITLE
Unable to use dependency since some classes are not accessable

### ISSUE THREAD

**Issue by StinkyLord** [LuiZiffer/ps2-census#1] opened 2020-12-19 22:10 UTC
Hi, 

Ive tried to use the maven dependency in my project, 
but ended up not being able to Query anything as some classes are private..

i just ended up forking your project xD

**Comment by LuiZiffer** [comment] 2021-07-06 13:13
Hey there, sorry for the rather late response. Could you tell me a bit more about this issue? I can't seem to find any private classes.

**Comment by PhilipAbed** [comment] 2021-07-06 13:24
That was long ago bro i cant remember exactly but, 
i added your code as a dependency, but was unable to call any event or any query..
i had to have the source code in order to make it work.. so basically its not usable, test it.. xD

anyway i'm already with some nice features on my bot after forking this. thanks a lot.

**Comment by LuiZiffer** [comment] 2021-07-06 14:33
Alright, since I am unable to reproduce this issue, and you have already resolved it for yourself, I'm going to close this issue now.

**Closed as completed by LuiZiffer** 2021-07-06 14:33 UTC
